### PR TITLE
updates on d3 graph visualization:

### PR DESCRIPTION
**Pull request by mef**
- added legend to explain the colors
- added title to show currently displayed dataset
- display the 'graph to load' select above the graph instead of the bottom the page
- switched to basic two-columns layout

### CODE REVIEW

**Comment by mef** [comment]
Thanks @mathieu1 :)

**Comment by peeterskris** [comment]
Hey guys, thanks for doing this work. For me index.html didn't work anymore though. So I reverted it back to more or less the original. index_tech.html is still doing what you guys were doing, if I understand correctly.

**Comment by mef** [comment]
interesting.

Some merge / conflict resolution may have failed, or it's a cross-browser compatibility issue.

index.html is supposed to look like this  (until commit 7b8e764):

screenshot - 121114 - 22 16 05

Works well for me in firefox and chrome, accessing files locally. @peeterskris:  in which browser did you have a problem, and was there any error message in the console?

**Comment by mathieu1** [comment]
I have index_tech.html woking on Firefox, but not Chrome. 

FIREFOX : only get the following warning : mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create

CHROME : I get the following errors:

XMLHttpRequest cannot load file:///mylocalfolder/SNA/meetups/html/topics_and_groups_graph_tech.json. Cross origin requests are only supported for protocol schemes: http, data, chrome-extension, https, chrome-extension-resource. d3.v3.min.js:1Ct.i.send d3.v3.min.js:1i.(anonymous function) d3.v3.min.js:1Ct d3.v3.min.js:1Bo.json d3.v3.min.js:5(anonymous function) VM46 index_tech.html?graphfile=topics_and_groups_graph_tech:81

Uncaught TypeError: Cannot read property 'nodes' of undefined VM46 index_tech.html?graphfile=topics_and_groups_graph_tech:86(anonymous function) VM46 index_tech.html?graphfile=topics_and_groups_graph_tech:86t d3.v3.min.js:1u d3.v3.min.js:1Ct.i.send d3.v3.min.js:1i.(anonymous function) d3.v3.min.js:1Ct d3.v3.min.js:1Bo.json d3.v3.min.js:5(anonymous function) VM46 index_tech.html?graphfile=topics_and_groups_graph_tech:81

Uncaught NetworkError: Failed to execute 'send' on 'XMLHttpRequest': Failed to load 'file:///mylocalfolder/SNA/meetups/html/topics_and_groups_graph_tech.json'. d3.v3.min.js:1Ct.i.send d3.v3.min.js:1i.(anonymous function) d3.v3.min.js:1Ct d3.v3.min.js:1Bo.json d3.v3.min.js:5(anonymous function) VM46 index_tech.html?graphfile=topics_and_groups_graph_tech:81

---

By the way, I removed the legend code from index_tech as there's a single category. (actually, there's some leftover code I forgot to remove at the end...)

**Comment by mathieu1** [comment]
Ok, found this which seems to answer the question. However, won't be testing it tonight.

http://stackoverflow.com/questions/10752055/cross-origin-requests-are-only-supported-for-http-error-but-im-loading-a-co

**Comment by mef** [comment]
@mathieu1 It's normal to get that error in Chrome, as stated in the stackOverflow thread. 

Starting chrome with the flag `--allow-file-access-from-files` is an easy fix, otherwise start the python server and browse from localhost:8000 `python -m SimpleHTTPServer`, as described in the solutions.

**Comment by peeterskris** [comment]
damn, looks nice. Although I'm afraid I've removed some of that code. Will look at putting it back. @mef : if you can fix it again, that would also be appreciated :-)

**Comment by mef** [comment]
I have some time to work on this today, I'll reset the feature and push it to a separate branch.

**Comment by mef** [comment]
@mathieu1 has restored the version with legend in a separate file: `index_full.html`. 

While index.html loads `force.json` file, `index_full.html` loads three different files from select menu, so I'm not sure whether same graphs are covered.

Two questions:
- @peeterskris : does `index_full.html` work for you ? (you first need to use the select menu to load a graph file)
- anyone who knows: what is `force.json` about? If its the same as `groups linked by common members` or `groups linked by common topics` then we may merge both html files, otherwise we can keep them separate (would be nice to have a description of which file contains what)

**Comment by mathieu1** [comment]
@mef : yes, it's a bit of a mess. Hopefully this helps (will push this in the relevant folder later):

| file | content | produced by |
| --- | --- | --- |
| `common_topic_graph.json` | groups linked by common topics | `topics.py` |
| `force.json` | _idem_ | `meetup_graphs.py` |
| `common_member_graph.json` | groups linked by common members | `topics.py` |
| `member_force.json` | _idem_ | `meetup_graphs.py` |
| `group.json` | nodes = BruDataSci + members + similar groups (common members), edges +-= membership | `meetup_graphs.py` |
| `topics_and_groups_graph.json` | nodes = topics + groups, edge = 'topic of' | `topics.py` |
| `topics_graph.json` | topics linked by common groups | `topics.py` |

`foo_tech.json` = same as `foo.json` restricted to tech meetup groups

N.B.: "A linked by common B" means that an edge between nodes A1 and A2 is drawn whenever the overlap between A1 and A2 is _substantial_ (substantial can have different meanings / thresholds for different graphs)

Technical N.B.: in `foo.json` (non-tech) there is only a `name`attribute which is displayed on mouseover only.
in `foo_tech.json`, the `name` attribute of a node is a shortened version of the `fullname` and is displayed on top of every node in `index_tech.html`.

**Pull request merged**
